### ISSUE TITLE
X axis wheel bolts hitting frame during leveling

### ISSUE THREAD

**Issue by LilJohnParadise** [bvanbreukelen/Ender3v2Precompiled#1]
Hello I have a problem with calibration, when it reaches right side of the bed the X axis goes to 254.0 and the nut on wheel hits the frame which disturbs whole axis and it measures wrong. Also I can't move X axis below 4.0. like it's 4.0 at end stop and not 0.0.

**Comment by bvanbreukelen** [comment]
Hi LilJohnParadise,

I compiled a new bin in which I made the printbed size smaller. (is was 235x235 mm) which is larger then recommended, but it works for me to use the complete printed. Maybe it just is not right for you. The 1.3.1-2-... version that you can download now has 225x225 mm as print bed size, which gives you more margins.

In case this doesn't work, let me know. Do you have an ender3 v2 with 4.2.7 or 4.2.2 motherboard? Make sure you use the correct BIN file, as a BIN file compiled for the 4.2.7 will cause errors/problem on a 4.2.2 motherboard and vice versa.

**Comment by LilJohnParadise** [comment]
I have Ender 3 V2 with 4.2.2 MB and used 4.2.2 binary. If I will move the probe offset a few mills back then I can get it to work eventually but probe is almost missing the bed on left side but then doesn't go up to 254.0 on right side. I'll flash 1.3.1-2 later today and report if it's alright. Thank you

**Comment by bvanbreukelen** [comment]
Hi,

No worries.. I just added a little info on the probe offset in the pervious comment.. Basically it is now set to -41(X) and -11(Y) which is perfect for my probe.. Perhaps you need a slightly different distance.. Just measure and change it in advanced setting.

**Comment by LilJohnParadise** [comment]
I also printed thingiverse mount and used -41 X and -11 Y offsets. I had no collision when I used -30 X offset but as I said on left side of the bed it was like few mm off the bed edge.
But you're right I'll measure actual distance between the nozzle and the tip of probe.
As for Z-offset mine is at -2.78 as there's new mount version which is 2mm shorter I guess.

**Comment by bvanbreukelen** [comment]
Ah. yes the new mount has a bit more clearance. 
For me the purge line in the beginning is also (and always) close to the edge, but I didn't encounter hitting the right side of the x axis. I thing the 225mm solves it. I just installed it for myself and did a level test to confirm. Everything is ok for me.

**Comment by LilJohnParadise** [comment]
When your X axis is at endstop then you get 4.0 reading and can't get below that to 0? That could be my problem because then it would get to 250.0 and probably wouldn't hit the frame?

**Comment by bvanbreukelen** [comment]
I just looked at mine.. Indeed it also goes to 4.0 and not to 0. No idea why that is the case.. 
Its not something I did as this is just the code from Jacob with the z-endstop for BLTOUCH enabled as option. 
Still even with 4.0 it doesn't cause an issue with me, als prints are fine.   Maybe I will test an older firmware from smith3d (before they switched to Jacob Jyers version) to see if it is the same there.

**Comment by MacadderUK** [comment]
Just noticed the size change on the bed, thank you so much for this. On another point is it normal for the x-axis to make a strange noise when moving. I never noticed it with bed leveling on Jyers firmware in the past.

**Comment by bvanbreukelen** [comment]
I looked it up why the y-axis is 4 and not 0. but this is default for marlin.

#define X_MIN_POS 4
#define Y_MIN_POS 7
#define Z_MIN_POS 0
#define X_MAX_POS (X_BED_SIZE + X_MIN_POS) + 15 // Extended max to allow the probe to reach more of the bed.
#define Y_MAX_POS (Y_BED_SIZE + Y_MIN_POS)
#define Z_MAX_POS 250

**Comment by bvanbreukelen** [comment]
Hi MacadderUK,

A strange noise is not something I hear on my Ender. (just tested).  What noise do you hear? Can you explain?
Just for clarity. This firmware that I compile, is the same version as you find on the Jyers GitHub,

The only thing I did is change one single line, where I uncommented the line below. This enables the Z-ENDSTOP to be used.

**#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN**

// Force the use of the probe for Z-axis homing
#define USE_PROBE_FOR_Z_HOMING

(Ok and the bed-size, as you have more bed-size then normally enabled by Creality ;). 

Strange sounds and things can happen in case you used the v4.2.7 firmware on the V4.2.2 ender. I compiled for both as my ender has a v4.2.7 motherboard.  Did you check?

**Comment by LilJohnParadise** [comment]
> I looked it up why the y-axis is 4 and not 0. but this is default for marlin. (edit: I looked this up in the config files from marlin)
> 
> #define X_MIN_POS 4
> #define X_MAX_POS (X_BED_SIZE + X_MIN_POS) + 15 // Extended max to allow the probe to reach more of the bed.

That would explain it, 4+235+15=254 and that's a tad too much for my printer. I just hear a knock when it goes to 254 and the BL touch senses 0.5mm higher bed level because whole thing shifts.

**Comment by bvanbreukelen** [comment]
I'm more than happy to compile a version with a bed-size of 231  mm for the X? (and for the Y its 7 mm  less so that would become 228) to try this out?  
I can also set this X_MIN positions to 0, but I think they are there for good reason

**Comment by bvanbreukelen** [comment]
I made two new versions :) (for 4.2.2 and 4.2.7)
With the prinbed-sizes like below. 

// The size of the print bed
#define X_BED_SIZE 231
#define Y_BED_SIZE 228

// Travel limits (mm) after homing, corresponding to endstop positions.
#define X_MIN_POS 4
#define Y_MIN_POS 7
#define Z_MIN_POS 0
#define X_MAX_POS (X_BED_SIZE + X_MIN_POS) + 15 // Extended max to allow the probe to reach more of the bed.
#define Y_MAX_POS (Y_BED_SIZE + Y_MIN_POS)
#define Z_MAX_POS 250

Let's get most of our print_bed volume ;-)

**Comment by LilJohnParadise** [comment]
Awesome, this 231x228 works great on my Ender! Now only calibrate to get reliable first layer with BLtouch. Thank you very much
