### ISSUE TITLE
Question: Do you plan to make more versions ?

### ISSUE THREAD

**Issue by vcrproszek** [bvanbreukelen/Ender3v2Precompiled#2]
Hey,

Thank so much for Z-endstop version of Jyres firmware. Do you plan to make more ? There is already a v2 of his firmware.

**Comment by bvanbreukelen** [comment]
Hi vcrproszak,

Thank you for your comment.. I myself have switched to a prusa printer a year ago. But I don't mind creating a new firmware version for the Z-endstop. I cannot however test it.

I will try to upload as soon as possible.

**Comment by vcrproszek** [comment]
Cool ! Thank you !
Good luck with prusa :)
